name: Optimize images

on:
  pull_request:
    branches: [ master, main, release/** ]
    paths:
      - "**/*.png"

  push:
    branches: [ master, main, release/** ]
    paths:
      - "**/*.png"

jobs:
  optimize-images:
    uses: Achrobat/Workflow-Repo/.github/workflows/optimize-images.yml@main
    secrets: inherit
